import time
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import json


class MyDriver():
    '''For login purpose, can store cookies for login nexttime
        login: 0: NOT recommended, possible login and verification needed when crawling data, causing interuption  1: Read the stored the cookie file only, NOT for first time usage   2: Recommended: get and store the cookie for next time usage, this requires to login manually.      More details to be seen in MyDriver.py'''
    def __init__(self, login, browser = 'Chrome'):
        '''Chrome is strongly recommended'''
        if browser == 'Edge':
            self.driver = webdriver.Edge()
        elif browser == 'Firefox':
            self.driver = webdriver.Firefox()
        else:
            option = webdriver.ChromeOptions()
            # Not load pics
            # option.add_experimental_option('prefs', {'profile.managed_default_content_settings.images': 2})
            self.driver = webdriver.Chrome(options= option)
            
        self.driver.implicitly_wait(10) 
        
        if login == 1:
            self.readcookie()
        elif login == 2:
            self.getcookie()
            self.readcookie()
            
        
    def getcookie(self):
        '''scan the QR code (do 2FA verification) to login mannually, wait until url to be www.jd.com'''

        self.driver.get('https://passport.jd.com/new/login.aspx?/')
        url='https://www.jd.com/'
        WebDriverWait(self.driver,500).until(EC.url_to_be(url))
        time.sleep(1.3)
        cookieList  = self.driver.get_cookies()
        cookieStr = json.dumps(cookieList)
        with open('Jdcookie.txt', 'w') as f:
            f.write(cookieStr)
        print('cookie wriiten into file "Jdcookie.txt"')

    def readcookie(self):
        '''if you have an file "Jdcookie.txt" generated by getcookie(), use this function to login.
            if you encounter some verification problem when logging in, just do it manually, the browser will wait for you to do so.'''
        self.driver.get('https://www.jd.com/')
        try:
            with open('Jdcookie.txt',mode='r',encoding='utf-8') as f:
                cookie = f.read()
            # from string format to dictionary in python
            cookie = json.loads(cookie)
            self.driver.delete_all_cookies()
            for item in cookie:
                self.driver.add_cookie(item)
        except:
            print('"Jdcookie.txt" file does not exist, try to set the login_status to 2!')
              
    def search_keyword(self, keyword):
        self.driver.get('https://www.jd.com')
        # self.driver.implicitly_wait(5)
        # input_box = self.driver.find_element(By.CSS_SELECTOR, '#key')
        input_box = WebDriverWait(self.driver, 15).until(\
            EC.presence_of_element_located((By.CSS_SELECTOR, '#key')))
        input_box.send_keys(keyword)
        time.sleep(0.1)
        input_box.send_keys(Keys.ENTER)
        # self.driver.implicitly_wait(15)
        time.sleep(0.2)
        
    def close(self):
        self.driver.close()

